import '../globals.css'
import { i18n } from '../../i18n-config'
import StyledComponentsRegistry from '../utils/registry';

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: {lang: string}
}) {
  return (
    <html lang={params.lang}>
      <StyledComponentsRegistry>
        <body>
          {children}
        </body>
      </StyledComponentsRegistry>
    </html>
  )
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
