import './globals.css';
import StyledComponentsRegistry from '../utils/registry';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body>
          {children}
        </body>
      </StyledComponentsRegistry>
    </html>
  )
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
