import { Footer, Header } from "@/components"
import { getLocalePartsFrom,ValidLocale, locales } from "i18n"
import "@/styles/_global.scss"

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode,
  params: { lang: ValidLocale; },
}) {
  
  return (
    <html lang="en">
      <body>
        <Header lang={lang}/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}

export async function generateStaticParams() {
  return locales.map((locale) => getLocalePartsFrom({ locale }))
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
